id: I4ED6CC66
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:58:41+00:00'
last_modified: '2022-06-07T21:33:20.982742+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5117
  title: སྤྱན་རས་གཟིགས་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་འགྲེལ་པ་པད་དཀར་དགྱེས་པའི་རང་གདངས། དེབ་ཕྲེང་བཞི་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C74E:
      image_group_id: I3CN5119
      title: ''
      total_pages: 170
      order: 1
      base_file: C74E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
