id: P004268
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5117
  title: སྤྱན་རས་གཟིགས་ཀྱི་སྒྲུབ་ཐབས་ཀྱི་འགྲེལ་པ་པད་དཀར་དགྱེས་པའི་རང་གདངས། དེབ་ཕྲེང་བཞི་པ།
  author: ''
  volumes:
    abf96bf403524a2584535ca4873469d2:
      image_group_id: I3CN5119
      title: ''
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
